#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
OUT="$ROOT/assets/golden_scene"
TMP="${RUNNER_TEMP:-/tmp}/frontline-golden-assets"
EXPORTER="$ROOT/tools/golden_scene/export_any_to_glb.py"

mkdir -p "$OUT/city" "$OUT/buildings" "$OUT/nature" "$OUT/vehicles" "$OUT/infantry" "$TMP"
rm -rf "$TMP"/*

curl_fetch() {
  local url="$1"
  local dest="$2"
  echo "FRONTLINE_ASSET_FETCH url=$url"
  curl -fL --retry 4 --retry-all-errors --retry-delay 2     -A "FRONTLINE-GoldenScene-V1/1.0" "$url" -o "$dest"
  test -s "$dest"
}

curl_fetch_fallback() {
  local dest="$1"
  shift
  for url in "$@"; do
    if curl_fetch "$url" "$dest"; then
      return 0
    fi
    rm -f "$dest"
  done
  echo "ERROR: all legal source URLs failed for $dest" >&2
  return 1
}

# ---------------------------------------------------------------------------
# CC0 settlement assets
# ---------------------------------------------------------------------------
curl_fetch   "https://opengameart.org/sites/default/files/kenney_city-kit-commercial_2.1.zip"   "$TMP/city.zip"
mkdir -p "$TMP/city"
unzip -q "$TMP/city.zip" -d "$TMP/city"

curl_fetch   "https://opengameart.org/sites/default/files/kenney_building-kit.zip"   "$TMP/building.zip"
mkdir -p "$TMP/building"
unzip -q "$TMP/building.zip" -d "$TMP/building"

# Nature Kit has moved between Kenney releases; both URLs point to the same
# CC0 family documented in the manifest. Failure is fatal: no primitive forest.
curl_fetch_fallback "$TMP/nature.zip"   "https://kenney.nl/media/pages/assets/nature-kit/37ac38a37b-1677698939/kenney_nature-kit.zip"   "https://opengameart.org/sites/default/files/Nature%20Kit%20%282.1%29.zip"
mkdir -p "$TMP/nature"
unzip -q "$TMP/nature.zip" -d "$TMP/nature"

copy_glb_family() {
  local source_dir="$1"
  local dest_dir="$2"
  local regex="$3"
  local count=0
  while IFS= read -r -d '' f; do
    local base
    base="$(basename "$f")"
    if [[ "$base" =~ $regex ]]; then
      # Names in Kenney packs are normally unique; prefix a deterministic index
      # to make collisions impossible across nested source directories.
      printf -v idx "%03d" "$count"
      cp "$f" "$dest_dir/${idx}_$base"
      count=$((count + 1))
    fi
  done < <(find "$source_dir" -type f -iname '*.glb' -print0 | sort -z)

  if (( count == 0 )); then
    # Some older archives use "GLTF format" but still carry .gltf + .bin.
    # Copy that full directory if no self-contained GLB exists.
    local gltf_dir
    gltf_dir="$(find "$source_dir" -type d -iname '*gltf*' | head -n 1 || true)"
    if [[ -n "$gltf_dir" ]]; then
      cp -R "$gltf_dir"/. "$dest_dir"/
      count="$(find "$dest_dir" -type f \( -iname '*.glb' -o -iname '*.gltf' \) | wc -l)"
    fi
  fi
  echo "FRONTLINE_ASSET_FAMILY_READY dest=$dest_dir count=$count"
  (( count > 0 ))
}

# Keep complete urban-building families but restrict nature to landscape assets
# useful in the proof to avoid vendoring hundreds of unrelated props.
copy_glb_family "$TMP/city" "$OUT/city" '.*'
copy_glb_family "$TMP/building" "$OUT/buildings" '.*'
copy_glb_family "$TMP/nature" "$OUT/nature" '([Tt]ree|[Bb]ush|[Rr]ock|[Gg]rass|[Pp]lant|[Ff]ence|[Hh]edge|[Tt]runk).*'

# ---------------------------------------------------------------------------
# Vehicle and infantry source models. Blender converts only legally
# redistributable source files to stable GLB so Godot users do not need Blender.
# ---------------------------------------------------------------------------
curl_fetch   "https://opengameart.org/sites/default/files/Tank.blend"   "$TMP/mbt.blend"
blender -b --python "$EXPORTER" --   --source "$TMP/mbt.blend"   --output "$OUT/vehicles/mbt.glb"

curl_fetch   "https://opengameart.org/sites/default/files/Recon_Tank.zip"   "$TMP/recon_tank.zip"
mkdir -p "$TMP/recon"
unzip -q "$TMP/recon_tank.zip" -d "$TMP/recon"
IFV_SRC="$(find "$TMP/recon" -type f \( -iname '*.blend' -o -iname '*.fbx' -o -iname '*.obj' \) | sort | head -n 1 || true)"
if [[ -z "$IFV_SRC" ]]; then
  echo "ERROR: Recon Tank archive contained no supported 3D source" >&2
  exit 21
fi
blender -b --python "$EXPORTER" --   --source "$IFV_SRC"   --output "$OUT/vehicles/ifv.glb"

curl_fetch   "https://opengameart.org/sites/default/files/soldier.zip"   "$TMP/soldier.zip"
mkdir -p "$TMP/soldier"
unzip -q "$TMP/soldier.zip" -d "$TMP/soldier"
SOLDIER_SRC="$(find "$TMP/soldier" -type f \( -iname '*.blend' -o -iname '*.fbx' -o -iname '*.obj' \) | sort | head -n 1 || true)"
if [[ -z "$SOLDIER_SRC" ]]; then
  echo "ERROR: soldier archive contained no supported 3D source" >&2
  exit 22
fi
blender -b --python "$EXPORTER" --   --source "$SOLDIER_SRC"   --output "$OUT/infantry/soldier.glb"

# Provenance snapshot: exact bytes used by this branch.
{
  echo "# FRONTLINE Golden Scene V1 source checksums"
  echo "# Generated by tools/golden_scene/bootstrap_assets.sh"
  sha256sum "$TMP/city.zip"
  sha256sum "$TMP/building.zip"
  sha256sum "$TMP/nature.zip"
  sha256sum "$TMP/mbt.blend"
  sha256sum "$TMP/recon_tank.zip"
  sha256sum "$TMP/soldier.zip"
} > "$OUT/SOURCE_CHECKSUMS.txt"

cat > "$OUT/.bootstrap_complete" <<'EOF'
TASK_ID=BUILD_GODOT_GOLDEN_SCENE_VISUAL_SPIKE_V1
ASSET_BOOTSTRAP=COMPLETE
LICENSE_MANIFEST=docs/production/GOLDEN_SCENE_V1_ASSET_MANIFEST.md
NO_RESTRICTED_SOURCE_ASSETS=YES
EOF

test -s "$OUT/vehicles/mbt.glb"
test -s "$OUT/vehicles/ifv.glb"
test -s "$OUT/infantry/soldier.glb"
test "$(find "$OUT/city" -type f \( -iname '*.glb' -o -iname '*.gltf' \) | wc -l)" -gt 0
test "$(find "$OUT/nature" -type f \( -iname '*.glb' -o -iname '*.gltf' \) | wc -l)" -gt 0

echo "FRONTLINE_GOLDEN_ASSET_BOOTSTRAP_PASS"
